[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pdf-security-patch"
version = "1.0.0"
description = "Mitigation DoS pour pypdf/PyPDF2 (CVE-2023-36810)"
authors = [{ name = "Phoenix Ecosystem" }]
requires-python = ">=3.9"
dependencies = [
  "pypdf>=3.9.0",
  "packaging>=23.0"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

