[tool.poetry]
name = "phoenix-ecosystem-workspace"
version = "1.0.0"
description = "Workspace orchestrator for the Phoenix Ecosystem. This is a meta-package and should not be installed directly."
authors = ["Matthieu Rubia <contact.phoenixletters@gmail.com>"]

# IMPORTANT : Il n'y a PAS de section [tool.poetry.packages] ici.

[tool.poetry.dependencies]
python = ">=3.9, <4.0"

# C'est la SEULE manière de déclarer vos paquets locaux.
# C'est direct, explicite et sans ambiguïté pour tous les outils.
phoenix_letters = { path = "apps/phoenix-letters", develop = true }
phoenix_event_bridge = { path = "packages/phoenix_event_bridge", develop = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"