# 🚀 Phoenix Ecosystem - Configuration Poetry Monorepo Finale
# Solution Gemini Pro Oracle pour Poetry + Streamlit Cloud

[tool.poetry]
name = "phoenix-ecosystem"
version = "1.0.0"
description = "Orchestrateur du monorepo pour l'écosystème Phoenix - Générateur IA reconversions"
authors = ["Matthieu Rubia <contact.phoenixletters@gmail.com>"]
readme = "README.md"

# Section cruciale : Poetry où trouver les vrais packages
packages = [
    { include = "phoenix_letters", from = "apps" },
    { include = "phoenix_event_bridge", from = "packages" },
]

[tool.poetry.dependencies]
python = ">=3.9"

# Dépendances de développement avec chemins relatifs (Poetry style)
phoenix_letters = { path = "apps/phoenix-letters", develop = true }
phoenix_event_bridge = { path = "packages/phoenix_event_bridge", develop = true }

[build-system]
# Backend Poetry pour monorepo
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"