[tool.poetry]
name = "phoenix-ecosystem"
version = "0.1.0"
package-mode = false # Indique que ce n'est pas un package installable en soi

[tool.poetry.dependencies]
python = ">=3.9, <4.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.4"
mypy = "^1.11.1"
pytest = "^8.3.3"
pre-commit = "^3.8.0"
pytz = "^2024.1"
python-dotenv = "^1.1.1"
google-generativeai = "^0.8.5"
pytest-mock = "^3.14.1"

 

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"