[tool.poetry]
name = "phoenix-ecosystem-workspace"
version = "1.0.0"
description = "Workspace orchestrator for the Phoenix Ecosystem. Not a package."
authors = ["Matthieu Rubia <contact.phoenixletters@gmail.com>"]

# LA LIGNE QUI DÉVERROUILLE TOUT
# "Poetry, utilise ce fichier pour gérer les dépendances, 
# mais n'essaie PAS d'installer le projet racine lui-même."
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9, <4.0"

# C'est la SEULE manière de déclarer vos paquets locaux.
# C'est direct, explicite et sans ambiguïté pour tous les outils.
phoenix_letters = { path = "apps/phoenix-letters", develop = true }
phoenix_cv = { path = "apps/phoenix-cv", develop = true }
phoenix_event_bridge = { path = "packages/phoenix_event_bridge", develop = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"