# ===================================================================
# PHOENIX ECOSYSTEM - INFRASTRUCTURE BLUEPRINT V2.0 (SYNTAXE MODERNE)
# ===================================================================

# Preview environments avec syntaxe moderne
previews:
  generation: automatic

services:
  # --- APPLICATIONS UTILISATEUR (WEB SERVICES) -----------------------

  - type: web
    name: phoenix-letters
    runtime: docker
    plan: starter

    # Dockerfile et contexte à la racine (unique)
    dockerfilePath: ./Dockerfile
    dockerContext: .
    rootDir: .

    dockerCommand: >
      streamlit run apps/phoenix-letters/main.py
      --server.port $PORT --server.address 0.0.0.0

    healthCheckPath: /_stcore/health
    autoDeployTrigger: commit

    buildFilter:
      # Déploie SEULEMENT si ces dossiers changent
      paths:
        - apps/phoenix-letters/**
        - packages/**
      # Et ignore explicitement les autres apps
      ignoredPaths:
        - apps/phoenix-cv/**
        - apps/phoenix-backend-unified/**
        - apps/phoenix-iris-api/**
        - apps/agent_ia/**

    envVars:
      - fromGroup: phoenix-secrets

  - type: web
    name: phoenix-cv
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    rootDir: .

    dockerCommand: >
      streamlit run apps/phoenix-cv/main.py
      --server.port $PORT --server.address 0.0.0.0

    healthCheckPath: /_stcore/health
    autoDeployTrigger: commit

    buildFilter:
      paths:
        - apps/phoenix-cv/**
        - packages/**
      ignoredPaths:
        - apps/phoenix-letters/**
        - apps/phoenix-backend-unified/**
        - apps/phoenix-iris-api/**
        - apps/agent_ia/**

    envVars:
      - fromGroup: phoenix-secrets

  - type: web
    name: phoenix-backend-unified
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    rootDir: .

    dockerCommand: python apps/phoenix-backend-unified/app.py

    healthCheckPath: /health
    autoDeployTrigger: commit

    buildFilter:
      paths:
        - apps/phoenix-backend-unified/**
        - packages/**
      ignoredPaths:
        - apps/phoenix-letters/**
        - apps/phoenix-cv/**
        - apps/phoenix-iris-api/**
        - apps/agent_ia/**

    envVars:
      - fromGroup: phoenix-secrets
      - key: ALLOWED_ORIGINS
        value: "https://phoenix-aube.vercel.app,https://phoenix-rise.vercel.app"
      - key: ENVIRONMENT
        value: "production"

  - type: web
    name: phoenix-iris-api
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    rootDir: .

    dockerCommand: python apps/phoenix-iris-api/main.py

    healthCheckPath: /health
    autoDeployTrigger: commit

    buildFilter:
      paths:
        - apps/phoenix-iris-api/**
        - packages/**
      ignoredPaths:
        - apps/phoenix-letters/**
        - apps/phoenix-cv/**
        - apps/phoenix-backend-unified/**
        - apps/agent_ia/**

    envVars:
      - fromGroup: phoenix-secrets

  - type: web
    name: phoenix-agents-ai
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    rootDir: .

    dockerCommand: python apps/agent_ia/main.py

    healthCheckPath: /health
    autoDeployTrigger: commit

    buildFilter:
      paths:
        - apps/agent_ia/**
        - packages/**
      ignoredPaths:
        - apps/phoenix-letters/**
        - apps/phoenix-cv/**
        - apps/phoenix-backend-unified/**
        - apps/phoenix-iris-api/**

    envVars:
      - fromGroup: phoenix-secrets
      - key: MAX_RESPONSE_TIME
        value: "30"
      - key: ENABLE_CLOUD_FALLBACK
        value: "true"

  # --- SERVICES BACKEND (WORKERS) -----------------------------------
  
  - type: worker
    name: phoenix-event-bridge
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    rootDir: .

    dockerCommand: python infrastructure/data-pipeline/app.py
    autoDeployTrigger: commit

    buildFilter:
      paths:
        - infrastructure/data-pipeline/**
        - packages/**
      ignoredPaths:
        - apps/**

    envVars:
      - fromGroup: phoenix-secrets
      - key: WORKER_TYPE
        value: "event_bridge"
      - key: ENABLE_EVENT_PROCESSING
        value: "true"

  - type: worker
    name: phoenix-user-profile
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    rootDir: .

    dockerCommand: python infrastructure/data-pipeline/app.py
    autoDeployTrigger: commit

    buildFilter:
      paths:
        - infrastructure/data-pipeline/**
        - packages/**
      ignoredPaths:
        - apps/**

    envVars:
      - fromGroup: phoenix-secrets
      - key: WORKER_TYPE
        value: "user_profile"

# --- INFRASTRUCTURE (BASE DE DONNÉES) ------------------------------

databases:
  - name: phoenix-db
    databaseName: phoenix_production
    plan: basic-1gb
    postgresMajorVersion: "15"

# --- GROUPES DE VARIABLES D'ENVIRONNEMENT -------------------------

envVarGroups:
  - name: phoenix-secrets
    envVars:
      - key: APP_ENV
        value: production
      - key: PYTHON_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      # Secrets (OPENAI_API_KEY, STRIPE_SECRET...) à ajouter via dashboard

