# 🌉 Phoenix Event Bridge - Configuration Poetry
# Package partagé pour Event-Sourcing Supabase

[tool.poetry]
name = "phoenix_event_bridge"
version = "1.0.0"
description = "Le bus d'événements partagé de l'écosystème Phoenix - Event-Sourcing avec Supabase"
authors = ["Matthieu Rubia <contact.phoenixletters@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"
supabase = "*"
python-dotenv = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"