name: 🔍 Audit Codex - Module Phoenix
description: Demande d’audit Codex ciblé sur un module Phoenix
title: "🔍 Audit Codex : [MODULE]"
labels: ["codex", "audit", "auto"]
body:
  - type: input
    id: module
    attributes:
      label: 📦 Module ciblé
      description: Nom du module à auditer (ex: phoenix-rise)
      placeholder: phoenix-rise
    validations:
      required: true

  - type: input
    id: base_branch
    attributes:
      label: 🌿 Branche de base
      description: Branche sur laquelle démarrer l’audit (ex: develop)
      placeholder: develop
    validations:
      required: true

  - type: checkboxes
    id: audit_focus
    attributes:
      label: 🎯 Cibles prioritaires
      options:
        - label: Sécurité & RGPD
        - label: Cohérence du code
        - label: UX & feedback utilisateur
        - label: Appels IA & performances
        - label: Refactoring & tests
        - label: Autre (précise dans les commentaires)

  - type: textarea
    id: context_info
    attributes:
      label: 📖 Infos supplémentaires (facultatif)
      description: Lien vers le fichier CONTEXT_CODEX_GENERAL.md ou précisions contextuelles
      placeholder: "docs/CONTEXT_CODEX_GENERAL.md"
