[tool.poetry]
name = "iris-client"
version = "0.1.0"
description = "Shared Iris Agent client for Phoenix ecosystem apps"
authors = ["Phoenix Team <team@phoenix.com>"]

[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.26"
streamlit = "^1.28"
pydantic = "^2.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"