[tool.poetry]
name = "phoenix-shared-ui"
version = "0.1.0"
description = "Shared UI components and design system for Phoenix applications."
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.9, <4.0"
streamlit = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
