[project]
name = "phoenix-shared-ui"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["phoenix_shared_ui*"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
